export const VACCINATIONSTATUS ="Vaccination status";
export const FIRSTDOSE ="1st dose completed";
export const SECONDDOSE ="2nd dose completed";
export const BOOSTERDOSE="Booster dose completed";
export const UPDATE ="Update";
export const LOGINPAGE ="Login page";
export const LOGIN ="Login";
export const SIGNUP ="Signup";
export const SYMPTOMS="Select your symptoms";
export const COLD="Cold";
export const COUGH="Cough";
export const FEVER ="Fever";
export const BP ="BP";
export const PAINS= "Body pains";
export const TASTE ="No taste";
export const SMELL =" No smell";
export const OXYGEN =" Low oxygen level";
export const TRACK ="Track";

